// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebService.Persistence;

namespace WebService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210321130510_InitMigraion")]
    partial class InitMigraion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebService.Entities.ComputerInfo", b =>
                {
                    b.Property<string>("ComputerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ConnectedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisconnectedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DotNetVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComputerName");

                    b.ToTable("ComputerInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
